name: Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev
    - name: Testing the code
      run: |
        PYTHONPATH=. pipenv run pytest \
          --cov=cipher \
          --cov-branch \
          --cov-report=term-missing \
          --cov-report=xml \
          --junitxml=junit.xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
          token: ${{ secrets.CODECOV_TOKEN }}

